project:
  type: website
  output-dir: docs

website:
  title: "psci3200-final-koung"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - FinalProjectResearchDesign.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

